version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always # always want nginx to restart on failure.
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
     - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # don't try to override this folder
      - ./server:/app # map references from server to app in current container
    
    #varibleName=value - populate value at RUNTIME
    environment:
      - REDIS_HOST=redis # gets the redis service's host URL.
      - REDIS_PORT=6379 # defaul redis port
      - PGUSER=postgres # default 
      - PGHOST=postgres # default
      - PGDATABASE=postgres # default
      - PGPASSWORD=postgres_password # default postgres database
      - PGPORT=5432 # default postgres port
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379

#started with docker-compose up --build